=== LostRot/Guia-32-XML-_V-lido/seccion_III/tarea.dtd
<!-- tarea dtd -->
<!ELEMENT grupo (team_trabajo+ | a*)*>
    <!ATTLIST grupo institucion CDATA #FIXED "Universidad de El Salvador">
<!ELEMENT team_trabajo (facultad| carrera| materia| profesor| nom_actividad| ponderacion| tema+| integrantes)+>
        <!ATTLIST team_trabajo tipo (GD | GL | GT) #REQUIRED>
        <!ATTLIST team_trabajo codigo NMTOKEN #REQUIRED>
    <!ELEMENT facultad (#PCDATA)>
        <!ATTLIST facultad id_facultad CDATA #REQUIRED>
    <!ELEMENT carrera (#PCDATA)>
        <!ATTLIST carrera id_carrera CDATA #REQUIRED>
    <!ELEMENT materia (#PCDATA)>
    <!ELEMENT profesor (#PCDATA)>
        <!ATTLIST profesor grupo (GD | GT | GL) #REQUIRED>
    <!ELEMENT nom_actividad (#PCDATA)>
    <!ELEMENT ponderacion (#PCDATA)>
    <!ELEMENT tema (#PCDATA)>
        <!ATTLIST tema n_grupo CDATA #REQUIRED>
    <!ELEMENT integrantes (alumno+)>
        <!ELEMENT alumno (carnet, nombre, apellido)>
            <!ATTLIST alumno coordinador (TRUE| FALSE) #REQUIRED>
            <!ATTLIST alumno numero CDATA #REQUIRED>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT apellido (#PCDATA)>
            <!ELEMENT carnet (#PCDATA)>
            <!ATTLIST alumno sexo (M | F) #REQUIRED>
            <!ELEMENT a (#PCDATA)>
	<!ATTLIST a  
		href CDATA #IMPLIED
		xmlns CDATA #IMPLIED 
		target (_blank|_self|marco) "_blank">

=== LostRot/Guia-32-XML-_V-lido/seccion_III/tarea.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- tarea.xml -->
<?xml-stylesheet type="text/css" href="tarea.css"?>

<!DOCTYPE grupo SYSTEM "tarea.dtd">
<grupo>
    <a xmlns="http://www.w3.org/1999/xhtml" href="/index.html" target="marco">index</a>

    <team_trabajo tipo="GD" codigo="1"> 
        <facultad id_facultad="12354">Faclutad de Ingenieria y Arquitectura</facultad>
        <carrera id_carrera="897">Ingenieria en sistemas informaticos</carrera>
        <materia>Proramacion I</materia>
        <profesor grupo="GD">ing. Balmore Ortiz</profesor>
        <nom_actividad>Evaluado 1</nom_actividad>
        <ponderacion>25%</ponderacion>
        <tema n_grupo="01">POO</tema>
        <integrantes>
            <alumno coordinador="TRUE" sexo="M" numero="01">
                <carnet>BE17005</carnet>
                <nombre>Erick Brandon</nombre>
                <apellido>Bolaños Elias</apellido>
            </alumno>
            <alumno coordinador="FALSE" sexo="M" numero="02">
                <carnet>AG19013</carnet>
                <nombre>Christian Javier</nombre>
                <apellido>Ayala Guerra</apellido>
            </alumno>
            <alumno coordinador="FALSE" sexo="M" numero="03">
                <carnet>AM10014</carnet>
                <nombre>Ricardo Antonio</nombre>
                <apellido>Acosta Morales</apellido>
            </alumno>
            <alumno coordinador="FALSE" sexo="F" numero="04">
                <carnet>AA19012</carnet>
                <nombre>Fatima Mercedes</nombre>
                <apellido>Aguilar Aguirre</apellido>
            </alumno>
        </integrantes>
    </team_trabajo>

    <team_trabajo tipo="GT" codigo="2"> 
        <facultad id_facultad="123">Faclutad de Ingenieria y Arquitectura</facultad>
        <carrera id_carrera="823">Ingenieria en sistemas informaticos</carrera>
        <materia>TPI115</materia>
        <profesor grupo="GT">ing. Balmore Ortiz</profesor>
        <nom_actividad>Evaluado 1</nom_actividad>
        <ponderacion>25%</ponderacion>
        <tema n_grupo="02">XML</tema>
        <integrantes>
            <alumno coordinador="TRUE" sexo="F" numero="01">
                <carnet>FL18015</carnet>
                <nombre>Elizabeth Rocio</nombre>
                <apellido>Fuentes Lopez</apellido>
            </alumno>
            <alumno coordinador="FALSE" sexo="M" numero="02">
                <carnet>OC12025</carnet>
                <nombre>Salvador Antonio</nombre>
                <apellido>Orantes carbajal</apellido>
            </alumno>
            <alumno coordinador="FALSE" sexo="M" numero="03">
                <carnet>LS12014</carnet>
                <nombre>Jorge Alonso</nombre>
                <apellido>Lopex Suares</apellido>
            </alumno>
            <alumno coordinador="FALSE" sexo="F" numero="04">
                <carnet>HM19025</carnet>
                <nombre>Sara Aide</nombre>
                <apellido>Hernandez Martinez</apellido>
            </alumno>
        </integrantes>
    </team_trabajo>

</grupo>
