<?xml version="1.0" encoding="UTF-8"?>
<!-- ejemplodtd1.xml -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?, telefono, correo, pais)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
			<!ATTLIST telefono tipo CDATA #REQUIRED>
		<!ELEMENT correo (#PCDATA)>
		<!ELEMENT pais (#PCDATA)>
			<!ATTLIST pais idioma CDATA #IMPLIED>
			<!ATTLIST pais moneda CDATA #IMPLIED> 
		]>
<fichero>
 	<ficha>
  		<nombre sexo="femenino" edad="17">Angelina</nombre>
  		<apellido>Fernandez</apellido>
  		<direccion>c/Ulises, 36</direccion>
  		<DUI>54986235-3</DUI>
  		<telefono tipo="celular">7456-2318</telefono>
		<correo>fermandez@mail.com</correo>
		<pais idioma="Español">El Salvador</pais>
 	</ficha>
</fichero>
