<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="/estilos/ejercicio-ii-1b-dtd.css" ?>
<!-- ejemplodtd1.xml -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (a*, encabezado?,ficha+)>
            <!ELEMENT encabezado (fecha, puesto)>
                <!ATTLIST encabezado empresa CDATA #FIXED "TPI S.A. de C.V.">
                <!ELEMENT fecha (#PCDATA)>
                <!ELEMENT puesto (#PCDATA)>
		    <!ELEMENT ficha ((nombre, apellido,foto?, direccion*, DUI?, telefono*) |correo|pais)*>
                <!ELEMENT foto EMPTY>
		        <!ELEMENT nombre (#PCDATA)>
		            <!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	    <!ATTLIST nombre edad  CDATA  #IMPLIED>
		        <!ELEMENT apellido (#PCDATA)>
		        <!ELEMENT direccion (#PCDATA)>
		        <!ELEMENT DUI (#PCDATA)>
		        <!ELEMENT telefono (#PCDATA)>
			        <!ATTLIST telefono tipo CDATA #REQUIRED>
                    <!ATTLIST telefono id CDATA #REQUIRED>
		        <!ELEMENT correo (#PCDATA)>
		        <!ELEMENT pais (#PCDATA)>
			        <!ATTLIST pais idioma CDATA #IMPLIED>
			        <!ATTLIST pais moneda CDATA #IMPLIED> 
				<!ELEMENT a (#PCDATA)>
				<!ATTLIST a  
					href CDATA #IMPLIED
					xmlns CDATA #IMPLIED 
					target (_blank|_self|marco) "_blank">
		]>
<fichero>

	<a xmlns="http://www.w3.org/1999/xhtml" href="/index.html" target="marco">INICIO</a>
    <encabezado>
		
        <fecha>09-09-2021</fecha>
        <puesto>Vendedora</puesto>
		
    </encabezado>
 	<ficha>
  		<nombre sexo="femenino" edad="17">Sara</nombre>
  		<apellido>Fuentes</apellido>
  		<direccion>Col. El vidente casa #9</direccion>
  		<DUI>5487964-1</DUI>
  		<telefono tipo="celular" id="1">6486-7318</telefono>
        <telefono tipo="fijo" id="2">2614-4587</telefono>
        <telefono tipo="celular" id="3">7563-4987</telefono>
		<correo>fuentes@mail.com</correo>
		<pais idioma="EspaÃ±ol">El Salvador</pais>
 	</ficha>
</fichero>