=== LostRot/Guia-32-XML-_V-lido/seccion_II/ejercicios/dtd_externa/dtd1a.dtd
<!-- dtd de ejercicio 1a -->
<!ELEMENT fichero (a*, ficha+)>
		<!ELEMENT ficha ((nombre, apellido, direccion*, DUI?, telefono) | correo | pais)*>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
			<!ATTLIST telefono tipo CDATA #REQUIRED>
		<!ELEMENT correo (#PCDATA)>
		<!ELEMENT pais (#PCDATA)>
			<!ATTLIST pais idioma CDATA #IMPLIED>
			<!ATTLIST pais moneda CDATA #IMPLIED>
		<!ELEMENT a (#PCDATA)>
		<!ATTLIST a  
			href CDATA #IMPLIED
			xmlns CDATA #IMPLIED 
			target (_blank|_self|marco) "_blank">

=== LostRot/Guia-32-XML-_V-lido/seccion_II/ejercicios/dtd_externa/ejercicio-ii-1a-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="/estilos/ejercicio-ii-1a-dtd.css" ?>
<!-- ejemplodtd1.xml -->

<!DOCTYPE fichero SYSTEM "dtd1a.dtd">
<fichero>
	<a xmlns="http://www.w3.org/1999/xhtml" href="/index.html" target="marco">INICIO</a>
 	<ficha>
  		<nombre sexo="femenino" edad="17">Angelina</nombre>
  		<apellido>Fernandez</apellido>
  		<direccion>c/Ulises, 36</direccion>
  		<DUI>54986235-3</DUI>
  		<telefono tipo="celular">7456-2318</telefono>
		<correo>fermandez@mail.com</correo>
		<pais idioma="Español">El Salvador</pais>
 	</ficha>
</fichero>
